//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RuValidation.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RuValidation.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Недопустимый символ в ИНН ФЛ.
        /// </summary>
        internal static string Inn_Individual_InvalidCharacter {
            get {
                return ResourceManager.GetString("Inn_Individual_InvalidCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Неверное контрольное число в ИНН ФЛ.
        /// </summary>
        internal static string Inn_Individual_InvalidHash {
            get {
                return ResourceManager.GetString("Inn_Individual_InvalidHash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Неверная длина ИНН ФЛ.
        /// </summary>
        internal static string Inn_Individual_InvalidLength {
            get {
                return ResourceManager.GetString("Inn_Individual_InvalidLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Недопустимое значение ИНН ФЛ.
        /// </summary>
        internal static string Inn_Individual_InvalidValue {
            get {
                return ResourceManager.GetString("Inn_Individual_InvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Недопустимое значение ИНН иностранного ЮЛ.
        /// </summary>
        internal static string Inn_Legal_Foreign_InvalidRange {
            get {
                return ResourceManager.GetString("Inn_Legal_Foreign_InvalidRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Недопустимый символ в ИНН ЮЛ.
        /// </summary>
        internal static string Inn_Legal_InvalidCharacter {
            get {
                return ResourceManager.GetString("Inn_Legal_InvalidCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Неверное контрольное число в ИНН ЮЛ.
        /// </summary>
        internal static string Inn_Legal_InvalidHash {
            get {
                return ResourceManager.GetString("Inn_Legal_InvalidHash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Неверная длина ИНН ЮЛ.
        /// </summary>
        internal static string Inn_Legal_InvalidLength {
            get {
                return ResourceManager.GetString("Inn_Legal_InvalidLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Недопустимое значение ИНН ЮЛ.
        /// </summary>
        internal static string Inn_Legal_InvalidValue {
            get {
                return ResourceManager.GetString("Inn_Legal_InvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Недопустимое значение ИНН местного ЮЛ.
        /// </summary>
        internal static string Inn_Legal_Local_InvalidRange {
            get {
                return ResourceManager.GetString("Inn_Legal_Local_InvalidRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Недопустимый символ в КПП.
        /// </summary>
        internal static string Kpp_InvalidCharacter {
            get {
                return ResourceManager.GetString("Kpp_InvalidCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Неверная длина КПП.
        /// </summary>
        internal static string Kpp_InvalidLength {
            get {
                return ResourceManager.GetString("Kpp_InvalidLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Недопустимое значение КПП.
        /// </summary>
        internal static string Kpp_InvalidValue {
            get {
                return ResourceManager.GetString("Kpp_InvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Недопустимый символ в нумерации паспорта гражданина РФ.
        /// </summary>
        internal static string LocalPassportNumber_InvalidCharacter {
            get {
                return ResourceManager.GetString("LocalPassportNumber_InvalidCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Неверная длина нумерации паспорта гражданина РФ.
        /// </summary>
        internal static string LocalPassportNumber_InvalidLength {
            get {
                return ResourceManager.GetString("LocalPassportNumber_InvalidLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Недопустимое значение нумерации паспорта гражданина РФ.
        /// </summary>
        internal static string LocalPassportNumber_InvalidValue {
            get {
                return ResourceManager.GetString("LocalPassportNumber_InvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Недопустимое значение ОГРН(ИП).
        /// </summary>
        internal static string Ogrn_InvalidValue {
            get {
                return ResourceManager.GetString("Ogrn_InvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Недопустимый символ в ОГРНИП.
        /// </summary>
        internal static string OgrnIndividual_InvalidCharacter {
            get {
                return ResourceManager.GetString("OgrnIndividual_InvalidCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Неверная контрольная сумма в ОГРНИП.
        /// </summary>
        internal static string OgrnIndividual_InvalidHash {
            get {
                return ResourceManager.GetString("OgrnIndividual_InvalidHash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Неверное число знаков в ОГРНИП.
        /// </summary>
        internal static string OgrnIndividual_InvalidLength {
            get {
                return ResourceManager.GetString("OgrnIndividual_InvalidLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Недопустимое значение ОГРНИП.
        /// </summary>
        internal static string OgrnIndividual_InvalidValue {
            get {
                return ResourceManager.GetString("OgrnIndividual_InvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Недопустимый символ в ОГРН.
        /// </summary>
        internal static string OgrnLegal_InvalidCharacter {
            get {
                return ResourceManager.GetString("OgrnLegal_InvalidCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Неверная контрольная сумма в ОГРН.
        /// </summary>
        internal static string OgrnLegal_InvalidHash {
            get {
                return ResourceManager.GetString("OgrnLegal_InvalidHash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Неверное число знаков в ОГРН.
        /// </summary>
        internal static string OgrnLegal_InvalidLength {
            get {
                return ResourceManager.GetString("OgrnLegal_InvalidLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Недопустимое значение ОГРН.
        /// </summary>
        internal static string OgrnLegal_InvalidValue {
            get {
                return ResourceManager.GetString("OgrnLegal_InvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Недопустимый символ в СНИЛС.
        /// </summary>
        internal static string Snils_InvalidCharacter {
            get {
                return ResourceManager.GetString("Snils_InvalidCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Неверное количество цифр в СНИЛС.
        /// </summary>
        internal static string Snils_InvalidDigitCount {
            get {
                return ResourceManager.GetString("Snils_InvalidDigitCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Неверный формат СНИЛС.
        /// </summary>
        internal static string Snils_InvalidFormat {
            get {
                return ResourceManager.GetString("Snils_InvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Неверное контрольное число в СНИЛС.
        /// </summary>
        internal static string Snils_InvalidHash {
            get {
                return ResourceManager.GetString("Snils_InvalidHash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Неверная длина СНИЛС.
        /// </summary>
        internal static string Snils_InvalidLength {
            get {
                return ResourceManager.GetString("Snils_InvalidLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Недопустимое значение СНИЛС.
        /// </summary>
        internal static string Snils_InvalidValue {
            get {
                return ResourceManager.GetString("Snils_InvalidValue", resourceCulture);
            }
        }
    }
}
